//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ParcelHubWebTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblReview
    {
        public int RevId { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public Nullable<int> ProdId { get; set; }
        public Nullable<int> AccId { get; set; }
    
        public virtual tblAccount tblAccount { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
